name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12', '14', '16']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: rm index.js && yarn jest index-test
      - run: yarn lint --max-warnings 0
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: node-${{ matrix.node-version }}
